### ISSUE TITLE
Preserve Line-breaks

### ISSUE THREAD

**Issue by TheDemystifier** [gregorrr/anki-auto-markdown#3]
It would been great if line breaks are preserved from original without having to add double-space or a `<br>` tag explicitly. 

Example :
```
Hello
World
```
Gives

> Hello
> World

without having to add `<br>` or double-space or anything like :
```
Hello<br>
World
```
I believe this is how it was done in Power Format Addon and I was used to that. Is there a way to tweak the addon to allow for this ?
Thanks!

**Comment by TheDemystifier** [comment]
Solved! Thank you for a well documented code. I just removed the double-spaces in LINE_BREAK_RE. I like it better this way. don't want to keep adding two spaces at the end of every line. Thanks!

**Comment by gregorrr** [comment]
I'm glad that you managed to find a solution. 

However I have to say that I cannot take credit for that piece of code! The project's 2 dependencies, pygments and markdown, are currently bundled with the code and the code you're referring to is part of the markdown project.
